export const REQUEST_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNING: 'ASSIGNING',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  EN_ROUTE: 'EN_ROUTE',
  ARRIVED: 'ARRIVED',
  SERVICE_STARTED: 'SERVICE_STARTED',
  SERVICE_COMPLETED: 'SERVICE_COMPLETED',
  CUSTOMER_NO_RESPONSE: 'CUSTOMER_NO_RESPONSE',
  MECHANIC_NO_SHOW: 'MECHANIC_NO_SHOW',
  SERVICE_CANCELLED: 'SERVICE_CANCELLED',
  REJECTED_BY_MECHANIC: 'REJECTED_BY_MECHANIC',
  NO_RESPONSE: 'NO_RESPONSE',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_ADMIN: 'CANCELLED_BY_ADMIN',
} as const;

export const CUSTOMER_CANCELLATION_REASONS = [
  'Problem solved',
  'Found another mechanic',
  'Price too high',
  'Wait time too long',
  'Wrong location',
  'Other',
] as const;

export const PARTNER_CANCELLATION_REASONS = [
  'Too far',
  'Wrong service',
  'Vehicle issue',
  'Already busy',
  'Emergency',
  'Other',
] as const;

export const QUOTE_STATUSES = {
  PENDING: 'QUOTE_PENDING',
  SUBMITTED: 'QUOTE_SUBMITTED',
  APPROVED: 'QUOTE_APPROVED',
  REJECTED: 'QUOTE_REJECTED',
} as const;

export const PAYMENT_STATUSES = {
  NOT_READY: 'PAYMENT_NOT_READY',
  PENDING: 'PAYMENT_PENDING',
  COMPLETED: 'PAYMENT_COMPLETED',
  FAILED: 'PAYMENT_FAILED',
} as const;
